// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person-service.proto

package com.protobuftest.protobuf;

public final class PersonProbuf {
  private PersonProbuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonResponse_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonResponse_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonResponse_CountryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonResponse_CountryInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024person-service.proto\")\n\rPersonRequest\022" +
      "\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\"\225\002\n\016PersonResp" +
      "onse\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005email\030" +
      "\003 \001(\t\022*\n\005phone\030\004 \003(\0132\033.PersonResponse.Ph" +
      "oneNumber\032F\n\013PhoneNumber\022\016\n\006number\030\001 \001(\t" +
      "\022\'\n\004type\030\002 \001(\0162\031.PersonResponse.PhoneTyp" +
      "e\0329\n\013CountryInfo\022\014\n\004name\030\001 \001(\t\022\014\n\004code\030\002" +
      " \001(\t\022\016\n\006number\030\003 \001(\005\"+\n\tPhoneType\022\n\n\006MOB" +
      "ILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\00227\n\rPersonServi" +
      "ce\022&\n\003Get\022\016.PersonRequest\032\017.PersonRespon" +
      "seB+\n\031com.protobuftest.protobufB\014PersonP" +
      "robufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PersonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PersonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonRequest_descriptor,
        new java.lang.String[] { "Name", "Id", });
    internal_static_PersonResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PersonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonResponse_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phone", });
    internal_static_PersonResponse_PhoneNumber_descriptor =
      internal_static_PersonResponse_descriptor.getNestedTypes().get(0);
    internal_static_PersonResponse_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonResponse_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_PersonResponse_CountryInfo_descriptor =
      internal_static_PersonResponse_descriptor.getNestedTypes().get(1);
    internal_static_PersonResponse_CountryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonResponse_CountryInfo_descriptor,
        new java.lang.String[] { "Name", "Code", "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
