// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person-service.proto

package com.protobuftest.protobuf;

public interface PersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .PersonResponse.PhoneNumber phone = 4;</code>
   */
  java.util.List<com.protobuftest.protobuf.PersonResponse.PhoneNumber> 
      getPhoneList();
  /**
   * <code>repeated .PersonResponse.PhoneNumber phone = 4;</code>
   */
  com.protobuftest.protobuf.PersonResponse.PhoneNumber getPhone(int index);
  /**
   * <code>repeated .PersonResponse.PhoneNumber phone = 4;</code>
   */
  int getPhoneCount();
  /**
   * <code>repeated .PersonResponse.PhoneNumber phone = 4;</code>
   */
  java.util.List<? extends com.protobuftest.protobuf.PersonResponse.PhoneNumberOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <code>repeated .PersonResponse.PhoneNumber phone = 4;</code>
   */
  com.protobuftest.protobuf.PersonResponse.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index);
}
