// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person-service.proto

package com.protobuftest.protobuf;

public interface PersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
